---
title: "Replication of 'Polluted Psyche: Is the Effect of Air Pollution on Unethical Behavior More Physiological or Psychological?' by Gong et al. (2020, Psychological Science)"
author: "Jordan Deasy (jdeasy3@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

I chose this experiment due to my interest in sustainability science and climate change more generally. I'm curious to explore consequences of climate change, specifically more niche/non-obvious ones, such as this one. Another interest of mine is ethics and moral philosophy, so exploring the effect of pollution (a major part of climate change) on human behavior (in this case, whether one acts ethically or not) immediately piqued my interest. <br />
The experiment I hope to be looking at focused on the relation between perceived air pollution and actual air pollution on unethical behavior. In the study, the researchers surveyed participants on their perceived severity of pollution (scale of 1-6) and sourced Air Quality Index (AQI) data from where the participants were for actual pollution data. For ethical behavior, participants were surveyed on questions such as "Today, I intentionally worked slower than I could have worked."
A challenge might be reporting on the actual air pollution (or this may not be a challenge, I'm unsure how easy that information is to access). Another challenge could be accurate reporting from participants on their own unethical behavior, as participants might underreport on their own bad actions. I anticipate that such surveys/data collection should not be particularly time intensive so I hope that will not be an issue. 

Repository: https://github.com/psych251/gong2020
Original Paper: https://github.com/psych251/gong2020/tree/main/original%20paper 

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
